Docs
nmkazantsev/seal_engine pull request #53
Opened 2024-09-09 12:59 UTC by nmkazantsev

чекай доку

2024-09-29 15:43 UTC, AntonMiklushov requested changes
SBTM

2024-09-29 15:43 UTC, AntonMiklushov commented on README.md
> +Данный движок приван:
Призван

2024-09-29 15:43 UTC, AntonMiklushov commented on README.md
> +В основе всего лежит идея многостраничного приложения, в котором  каждой страницы есть свои локальные переменные, удаляемые при ее закртытии. Такой подход позволит абстрагироваться от других страниц,
Закртытии

2024-09-29 15:43 UTC, AntonMiklushov commented on README.md
> +Это абстрактный класс, при реализации значения, находящегося в видео памяти (uniform переменная) нужно от нгео унаследоваться и переопределить
Видеопамять нгео

2024-09-29 15:43 UTC, AntonMiklushov commented on README.md
> +`Shape(String fileName, String textureFileName, GamePageInterface page)` - конструктор с ассинхронной подгрузкой файла вершин и синхронной (в основном потоке) загрузкой текстуры
Асинхронный

2024-09-29 15:43 UTC, AntonMiklushov commented on README.md
> +`delete()` - очистка видео памяти.
Видеопамять

2024-09-29 15:43 UTC, AntonMiklushov commented on README.md
> +В основе лежит реализация с learn opengl. Созданы классы источников света, по набору переменных дублирующие структуры эттх источников в дефолтном шейдере освещения.
Этттх

2024-09-29 15:43 UTC, AntonMiklushov commented on README.md
> +Кодна нужно, объекты света используют вызовы записи в uniform переменную,адреса которой они получают напрямую из шейдера. Вызов getLocations() инициируется классом ShaderData.
Кодна нужен, да

2024-10-01 10:47 UTC, nmkazantsev commented
ладно, не буду тебя мучать, просто посмотри, что я все закрыл и нажми аппрув
SGTM

2024-10-01 13:13 UTC, merged

2024-10-01 13:14 UTC, nmkazantsev commented
я тебя не дождался. сорри

2024-10-03 05:14 UTC, AntonMiklushov approved these changes